### ISSUE TITLE
获取文件名为 null

### ISSUE THREAD

**Issue by maxming2333** [node-modules/wt#7]
type: `bug`

scope: `node_modules\wt\index.js:240:11`

bug:
在修改文件时，服务器报错，后来打long发现，传入滴`name`竟然是`null`

log 如下

```
e:\git\xxx\node_modules\wt\index.js:240
  if (name[0] === '.' && this._ignoreHidden) {
          ^

TypeError: Cannot read property '0' of null
    at Watcher.proto._handle (xxx\node_modules\wt\index.js:240:11)
    at emitTwo (events.js:87:13)
    at FSWatcher.emit (events.js:172:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1221:12)
2016-03-21 17:03:42,380 ERROR 15304 nodejs.AgentWorkerDiedError: AgentWorkerDiedError: [master] agent worker 14888 died (code: 1, signal: null)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

目前处理方法是 在 `xxx\node_modules\wt\index.js:240:11` 加一个判断

```
if (!name) {
  return;
}
```

--------

node v4.2.4

Window 10 64-bit

**Comment by fengmk2** [comment]
Fixed 037a4e409bc0a64c452a9ef45b508ed87efefafd
